########################################################
#                 CONFIGURATION FILE                   #
#                   FAKECONNECTION                     #
#                      TEDVAL88                        #
# http://dev.bukkit.org/bukkit-plugins/fakeconnection/ #
########################################################

Messages:
   'Co': "joined the game."
   'Deco': "left the game."
   'AFK': "is now AFK."
   'nAFK': "is no longer AFK."
Others:
   'mcstats': "true"

   Hello it's me !
